name: Build apk

on:
  push:
    branches: [ "develop" ]
    tags-ignore: ["v*"]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug apk
      run: ./gradlew assembleDebug

    - name: Rename APK file
      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/m_android_debug.apk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: m_android_debug.apk
        path: app/build/outputs/apk/debug/m_android_debug.apk 

    - name: Copy APK to repository
      run: cp app/build/outputs/apk/debug/m_android_debug.apk ./
      
    - name: Commit APK with tag
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add m_android_debug.apk
        git commit -m "Add built m_android_debug.apk"
        git tag v1.0-$(date +'%Y%m%d%H%M%S')
        git push origin develop --tags  
