name: Build apk

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APK_PATH: apk/debug
      APK_NAME: "m_android_debug-$(date +'%Y%m%d%H%M%S').apk"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop  # Вказуємо гілку develop для checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug apk
        run: ./gradlew assembleDebug

      - name: Rename APK file
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ env.APK_NAME }}

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/debug/${{ env.APK_NAME }}

      - name: Copy APK to repository
        run: |
          mkdir -p ./${{ env.APK_PATH }}
          cp app/build/outputs/apk/debug/${{ env.APK_NAME }} ./${{ env.APK_PATH }}/

      - name: Commit APK with tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./${{ env.APK_PATH }}/${{ env.APK_NAME }}
          git commit -m "Add built ${{ env.APK_NAME }} [skip ci]"
          git push origin develop